# Generated by Django 4.2.3 on 2023-07-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_session_keys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tag',
            field=models.JSONField(default=dict),
        ),
    ]
