# Generated by Django 4.2.3 on 2023-07-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_userprofile_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tag_permission',
            field=models.TextField(default='None'),
        ),
    ]
