version: "3"
services:
  judge-server:
    image: registry.cn-hangzhou.aliyuncs.com/onlinejudge/judge_server
    container_name: judge-server
    restart: always
    read_only: true
    cap_drop:
      - SETPCAP
      - MKNOD
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP
      - FSETID
    tmpfs:
      - /tmp
    volumes:
      - ./data_dev/backend/test_case:/test_case:ro
      - ./data_dev/judge_server/log:/log
      - ./data_dev/judge_server/run:/judger
    environment:
      # 修改SERVICE_URL
      - SERVICE_URL=http://127.0.0.1:8080
      # 修改BACKEND_URL
      - BACKEND_URL=http://127.0.0.1:8000/api/judge_server_heartbeat/
      # TOKEN和运行后端时设置的TOKEN相同
      - TOKEN=1ac98198e240e322069a52a9dd65d0ed
      # - judger_debug=1
    network_mode: "host"
